site_name: Practy
site_url: http://127.0.0.1:8000/

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

nav:
  - Home: index.md
  - Running Programs:
    - Running Python: languages/running_python.md
    - Running JavaScript: languages/running_javascript.md
  - Topics:
    - Elementary Programming:
      - Elementary Programming Exercises: topics/elementary_programming/exercises.md
      - Elementary Programming Questions: topics/elementary_programming/questions.md
